-- Rename Category enum values to match Eboya Boi product lines
ALTER TYPE "Category" RENAME VALUE 'SHOES' TO 'KAFTAN';
ALTER TYPE "Category" RENAME VALUE 'BAGS' TO 'AGBADA';
ALTER TYPE "Category" RENAME VALUE 'CLOTHING' TO 'SHIRTS';
ALTER TYPE "Category" RENAME VALUE 'ACCESSORIES' TO 'TWO_PIECE';
ALTER TYPE "Category" ADD VALUE IF NOT EXISTS 'CASUALWEAR';
